### ISSUE TITLE
Multi-threading support

### ISSUE THREAD

**Issue by kocica** [nmcl/C--SIM#58]
Hello @nmcl,

does the library support multi-threading? It seems to me like it might have, but then I saw singleton `Scheduler` which could break multi-threading.

By multi-threading, I mean to run multiple simulations at the same time. E.g. using OpenMP.

Thank you for answer.

**Comment by kocica** [comment]
By multi-threading, I mean to run multiple simulations at the same time. E.g. using OpenMP.

**Comment by kocica** [comment]
Seems like the `Scheduler` singletop might not be a problem, but the problem probably is, only one `Process` can be active at the time. Can you confirm?

**Comment by nmcl** [comment]
Hi there. Yes, it's the same approach that SIMULA has/had: only one Process is active at a time but each Process is modelled as a separate thread.

**Comment by kocica** [comment]
So there is no way to run multiple simulations truly simultaneously right? Are you aware of some library which would support it? I'm currently (for my thesis) developing an genetic algorithm (GA) optimizer (for a warehouse operations), which is running ~100.000 of warehouse simulations per each GA iteration, so it's really a big bottleneck and since my current simulation library (SIMLIB/C++) only uses one thread, we cannot even run it on school cluster with a lot of cores, because it always uses only one thread. As you said, each process is modelled as a separate thread - does it imply any speedup, when only one process can be active at the time? It seems to me like it wouldn't be much faster then one-thread simulation library. Thank you for reply.

**Comment by nmcl** [comment]
I'm not aware of anything which would allow running of multiple simulations within the same operating system process, but that doesn't mean they don't exist. However, that was never the model for C++SIM (or JavaSim) which were based on SIMULA. One thing you could do, of course, is run multiple operating system processes concurrently and tie them to physical CPU threads, i.e., run multiple instances of C++SIM at the same time.

**Comment by kocica** [comment]
I will give a change to OMNeT++ library and if it doesn't work neither, I will have to do what you said - run multiple instances of the simulator :) Thank you for your help :)

**Comment by nmcl** [comment]
Glad to help!

**Comment by kocica** [comment]
One more question @nmcl :) Is there any mechanism of "facilities" and seizing them in the C++SIM? For example if there would be customers (processes) generated each ~10 seconds and they would like to seize one facility, let's say cash register. In case the cash register would be already seized by another customer (process), the other customers would have to wait (be passivated) until the cash register is free for them. I was searching through the docs and code but haven't found anything similar to this mechanism, does it mean I would have to implement it my self using Queues etc.?

**Comment by nmcl** [comment]
C++SIM simulations use the concept of "virtual time" where the clock ticks don't have to represent seconds, say. You'll find that in the doc. With that in mind though, if you check out the Event classes you'll find Semphores and TriggerQueues which might be what you need.
